### ISSUE TITLE
Poland mobility reports

### ISSUE THREAD

**Issue by BERENZ** [datasciencecampus/mobility-report-data-extractor#4]
I tried to follow your code to extract data for Poland but unfortunately the `getgraphs.py` does not extract graphs from the main svg plot. It works for other countries (i.e. I have checked G20 files that you provided) but not in my case. 

**To Reproduce**
I attached the pdf file along with zipped svg file generated by Affinity Designer 1.6.5. 

[2020-03-29_PL_Mobility_Report_en.pdf](https://github.com/datasciencecampus/mobility-report-data-extractor/files/4433067/2020-03-29_PL_Mobility_Report_en.pdf)
[poland.svg.zip](https://github.com/datasciencecampus/mobility-report-data-extractor/files/4433069/poland.svg.zip)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina (10.15.3)

**Comment by mshodge** [comment]
Thank you @BERENZ we will look at this as soon as we can.

**Comment by mshodge** [comment]
@BERENZ when I convert the PDF to SVG it all works ok. It must have changed the default Affinity Designer settings somewhere (I've been using it for a while, so that's not surprising). Below are the screenshots of the loading of the PDF and saving of the SVG. There are no steps in between. Could you compare to your settings so I can isolate the issue and add any non-default settings to the guide please. We also found that it works with the latest Affinity Designer, but the SVG saving option is (for digital). I have also attached my document SVG for reference.

# Load

<img width="637" alt="Screenshot 2020-04-06 at 07 33 29" src="https://user-images.githubusercontent.com/15108577/78529354-5079f580-77d9-11ea-9efc-81693df607c0.png">

# Save

<img width="633" alt="Screenshot 2020-04-06 at 07 33 46" src="https://user-images.githubusercontent.com/15108577/78529363-54a61300-77d9-11ea-9ad3-8c141c293daa.png">

# SVG

[Poland_dsc.svg.zip](https://github.com/datasciencecampus/mobility-report-data-extractor/files/4436166/Poland_dsc.svg.zip)

**Comment by mshodge** [comment]
@BERENZ and yes, I originally tried with your SVG, and it didn't work. So it must be something to do with the SVG creation. This is a little temperamental at the moment. We wanted to use an automated method like pdftocairo but the matrix transformations were crazy - and each SVG creator seems to choose it's own change to the stroke-width of the lines, and whether it uses HEX values, RGB % etc.

**Comment by BERENZ** [comment]
@mshodge thank you for prompt answer. I'll check the file and Affinity, thanks!. I also tried `pdf2svg` but it create separate svg for each plot in the pdf.

**Comment by mshodge** [comment]
That may work with our code using `-m` in `getgraphs.py` I'll test it out too as Affinity throws up some other bugs like #5 for us at the moment.

**Comment by BERENZ** [comment]
@mshodge I confirm that the codes works smoothly, thank you!

**Comment by mshodge** [comment]
No problem, thanks @BERENZ. We aim to make the pipeline better soon with pre-made SVGs to eliminate the errors (I've spent a day working with transformations and it's a killer)
